[package]
name = "baby-race"
version = "0.1.0"
edition = "2021"

[dependencies]
evenio = "0.6"
geng.git = "https://github.com/geng-engine/geng"
serde = "1"

[patch.crates-io]
async-broadcast = { git = "https://github.com/kuviman/async-broadcast", branch = "fix-wasm-again" }

