background_color = "#778C53"
sensitivity = 0.1
ruler_color = "white"
track_len = 2
nametag_color = "#000a"
nametag_size = 0.5
nametag_offset = 0.9

[outline]
scale = 1.1
color = "black"
hovered_color = "green"
air_color = "#77f"
ground_highlight_radius = 0.1
ground_color = "#0004"

[ui]
edit_text_color = "#affa"
fov = 20
label_color = "#444"
button_color = "black"
hover_color = "#fff7"
text_offset = 0.2
rank_color = "#222"
rank_offset = 2
rank_size = 2
timer_color = "black"
timer_size = 1

[camera]
fov = 20
speed = 10

[baby]
radius = 0.5
head_offset = [0, 1]
max_head_rotation = 40
head_rotation_k = 0.3
arm_offset = [-0.5, 0.5]
leg_offset = [-0.4, -0.8]
limb_rotation_limit = 50
limb_length = 0.5
[baby.limbs.RightArm]
angle = 45
body_pos = [0.5, 0.5]
texture_origin = [0, 0]
touch_ground = [0.7, 0.9]
flip = true
[baby.limbs.LeftArm]
angle = 135
body_pos = [-0.5, 0.5]
texture_origin = [0, 0]
touch_ground = [-0.7, 0.9]
flip = false
[baby.limbs.RightLeg]
angle = -45
body_pos = [0.4, -0.7]
texture_origin = [0, 0]
touch_ground = [0.7, -0.7]
flip = true
[baby.limbs.LeftLeg]
angle = -135
body_pos = [-0.4, -0.7]
texture_origin = [0, 0]
touch_ground = [-0.7, -0.7]
flip = false
