background_color = "#777"
fov = 20

[baby]
radius = 1
head_offset = [0, 1]
arm_offset = [-0.5, 0.5]
leg_offset = [-0.4, -0.8]
limb_rotation_limit = 30
[baby.limb_angles]
RightArm = 45
LeftArm = 135
RightLeg = -45
LeftLeg = -135
