background_color = "#777"
sensitivity = 0.1

[info]
tiny_scale = 0.2
timer_size = 2
timer_color = "black"
join_offset = [0, -2]
join_color = "black"
join_size = 1

[camera]
fov = 20
speed = 10

[baby]
radius = 1
head_offset = [0, 1]
max_head_rotation = 40
head_rotation_k = 0.3
arm_offset = [-0.5, 0.5]
leg_offset = [-0.4, -0.8]
limb_rotation_limit = 30
limb_length = 0.5
[baby.limbs.RightArm]
angle = 45
body_pos = [0.5, 0.5]
touch_ground = [0.5, 0.5]
flip = true
[baby.limbs.LeftArm]
angle = 135
body_pos = [-0.5, 0.5]
touch_ground = [-0.5, 0.5]
flip = false
[baby.limbs.RightLeg]
angle = -45
body_pos = [0.4, -0.7]
touch_ground = [0.5, -0.5]
flip = true
[baby.limbs.LeftLeg]
angle = -135
body_pos = [-0.4, -0.7]
touch_ground = [-0.5, -0.5]
flip = false
